name: Unpack IMG (Boot only, with MediaFire support)3

on:
  workflow_dispatch:
    inputs:
      mediafire_url:
        description: "URL file (.img.gz / .img.xz / .img.7z) di MediaFire"
        required: true
        default: "https://www.mediafire.com/file/xxxxxx/firmware.img.xz/file"
      output_name:
        description: "Nama prefix hasil ekstraksi"
        required: false
        default: "openwrt"
      release_tag:
        description: "Tag release untuk upload hasil"
        required: false
        default: "unpack-boot"

jobs:
  unpack-boot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # dibutuhkan untuk upload ke Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils p7zip-full kpartx util-linux mount parted zip jq

      - name: Resolve MediaFire direct link
        id: resolve
        run: |
          echo "🔍 Resolving MediaFire link..."
          URL="${{ inputs.mediafire_url }}"
          DIRECT=$(curl -sL "$URL" | grep -oE 'https://download[^"]+' | head -n1)
          if [ -z "$DIRECT" ]; then
            echo "❌ Tidak bisa mendapatkan direct link dari MediaFire"
            exit 1
          fi
          echo "✅ Direct link: $DIRECT"
          echo "direct_url=$DIRECT" >> $GITHUB_OUTPUT

      - name: Download compressed image
        run: |
          echo "🔽 Downloading image..."
          curl -L -o "firmware.img.download" "${{ steps.resolve.outputs.direct_url }}"
          echo "📦 File hasil unduhan:"
          ls -lh

          EXT=$(file firmware.img.download | grep -Eo 'XZ|gzip|7-zip' | head -n1 | tr 'A-Z' 'a-z')
          case "$EXT" in
            xz) mv firmware.img.download "${{ inputs.output_name }}.img.xz" ;;
            gzip) mv firmware.img.download "${{ inputs.output_name }}.img.gz" ;;
            7-zip) mv firmware.img.download "${{ inputs.output_name }}.img.7z" ;;
            *) echo "❌ Format tidak dikenali ($EXT)"; exit 1 ;;
          esac

      - name: Extract image (.gz / .xz / .7z)
        run: |
          FILE=$(ls *.img.* | head -n1)
          echo "📦 Extracting $FILE..."
          case "$FILE" in
            *.gz) gunzip -v "$FILE" ;;
            *.xz) xz -d -v "$FILE" ;;
            *.7z) 7z x "$FILE" ;;
            *) echo "❌ Format tidak dikenali."; exit 1 ;;
          esac
          ls -lh

      - name: Extract boot partition only
        run: |
          set -e
          IMG=$(ls *.img | head -n1)
          mkdir -p boot mnt

          echo "🧩 Setting up loop device..."
          LOOP=$(sudo losetup --show -Pf "$IMG")
          echo "Using loop device: $LOOP"

          echo "🔍 Listing partitions..."
          sudo fdisk -l "$LOOP" || true

          echo "📂 Mounting boot partition..."
          if sudo mount "${LOOP}p1" mnt 2>/dev/null; then
            if [ -d mnt/boot ]; then
              cp -a mnt/boot/* boot/ || true
            else
              cp -a mnt/* boot/ || true
            fi
            sudo umount mnt
          else
            echo "❌ Tidak bisa mount partisi boot (p1)"
            exit 1
          fi

          sudo losetup -d "$LOOP"
          echo "✅ Boot folder extracted."
          du -sh boot || true
          ls -lh boot | head -n 10

      - name: Compress boot folder
        run: |
          echo "🗜️ Compressing boot folder..."
          zip -r "${{ inputs.output_name }}_boot.zip" boot
          ls -lh *.zip

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-${{ inputs.output_name }}
          path: ${{ inputs.output_name }}_boot.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          files: ${{ inputs.output_name }}_boot.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
